# Generated by Django 5.2.1 on 2025-06-01 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a profile picture. Supported formats: jpg, png, webp.', max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
