# Generated by Django 5.2.1 on 2025-05-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
    ]
