# Generated by Django 5.2.1 on 2025-05-30 06:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_ad_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the ad. Supported formats: jpg, png, webp.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
