# Generated by Django 5.2.1 on 2025-05-27 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_customtag_customuuidtaggeditem_alter_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Check to mark this news as trending.'),
        ),
        migrations.CreateModel(
            name='TrendingNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the news is currently trending.')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='news.news')),
            ],
            options={
                'verbose_name_plural': 'Trending News',
                'ordering': ['-added_at'],
            },
        ),
    ]
