# Generated by Django 5.2.1 on 2025-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options_news_is_trending_trendingnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_carousel',
            field=models.BooleanField(default=False, help_text='Check to include this news in the carousel.'),
        ),
    ]
