# Generated by Django 5.2.1 on 2025-06-02 15:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the news article. Supported formats: jpg, png, webp.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
